### PR TITLE
Adding recipes for Quarkus

### PR DESCRIPTION
**Pull request by harshmadhani**
This is a PR to add recipes for Quarkus

### CODE REVIEW

**Comment by harshmadhani** [comment]
cc @stuartwdouglas

**Comment by harshmadhani** [comment]
@daveconde Can you merge the PR ? I do not have the permissions to merge it.

**Comment by daveconde** [comment]
@harshmadhani I don't have merge access unfortunately.

**Comment by harshmadhani** [comment]
@daveconde Okay. @stuartwdouglas Can you help us with the merge?

**Review by stuartwdouglas — APPROVED** [review]

**Pull request merged**
