### PR TITLE
Fix msv build on JDK 8

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by dwalluck** [comment]
Aside from deleting it, I think we can find it in some other jar like jaxb-xjc. Or we can switch it to use the open source versions which I think are part of Apache xml resolver.

**Comment by stuartwdouglas** [comment]
Will this build work with JDK7?

**Comment by dwalluck** [comment]
With those internal classes removed, it will build on JDK 7. But those classes still don't exist in JDK 7.

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
Instead of deleting this can you change it to something like:

    sed -i s/com.sun.org.apache.xml.internal.resolver.tools.CatalogResolver/org.apache.xml.resolver.tools.CatalogResolver/ msv/src/main/java/com/sun/msv/driver/textui/Driver.java

**Comment by dwalluck** [comment]
> Instead of deleting this can you change it to something like:

OK, that's what I meant by the xml resolver above, actually. It looks like it doesn't add an additional dependency either.

**Comment by dwalluck** [comment]
Along with the class change and updating the version of maven-bundle-plugin (and skipping javadoc), the build now works on JDK 8.

**Comment by stuartwdouglas** [comment]
What is the issue with the maven bundle plugin?

**Comment by dwalluck** [comment]
```
[INFO] --- maven-bundle-plugin:1.4.3:bundle (default-bundle) @ msv-core ---
[ERROR] Error building bundle net.java.dev.msv:msv-core:bundle:2011.1 : Unresolved references to [javax.xml] by class(es) on the Bundle-Classpath[Jar:dot]: [com/sun/msv/reader/xmlschema/WSDLSchemaReader$SimpleNamespaceContext.class, com/sun/msv/reader/xmlschema/WSDLSchemaReader.class, com/sun/msv/reader/xmlschema/XMLSchemaReader.class]
[ERROR] Error(s) found in bundle configuration
```

**Pull request merged**
